import Head from "next/head";
import Film from "../components/Film";
import Films from "../components/Films";
import Homeworld from "../components/Homeworld";

// write the type for our character
type Character = {
  name: string;
  height: string;
  mass: string;
  hair_color: string;
  skin_color: string;
  eye_color: string;
  birth_year: string;
  gender: string;
  homeworld: string;
  films: string[];
  species: string[];
  vehicles: string[];
  starships: string[];
  created: string;
  edited: string;
  url: string;
};

// write the type for our props
type CharacterProps = {
  character: Character;
};

export default function Home({ character }: CharacterProps) {
  // type our props
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto p-16 text-gray-900">
        <h1 className="font-bold text-4xl text-center">
          Welcome to <a href="https://nextjs.org">Next.js + Typescript!</a>
        </h1>
        <div className="py-8">
          {/* pass our character data from the props as we normally would */}
          <h2 className="font-semibold text-2xl">{character.name}</h2>

          {/* example of passing data to a component */}
          <p className="font-mono font-semibold text-xl pt-4">Home World</p>
          <Homeworld worldUrl={character.homeworld} />

          {/* example of mapping over an array and returning multiple components */}
          <p className="font-mono font-semibold text-xl pt-4">Films</p>
          {character.films.map((film, index) => (
            <Film key={index} url={film} />
          ))}
        </div>
      </main>
    </div>
  );
}

export async function getStaticProps() {
  // normal fetch request
  let res = await fetch("https://swapi.dev/api/people/1");
  // type the response json object as type Character
  let character: Character = await res.json();

  return {
    props: { character }, // will be passed to the page component as props
  };
}
